## Programming Basic Assignment 7

### 1. Write a Python Program to find sum of array?

In [2]:
from numpy import random

x = random.randint(100,size=5)

sum=0

for i in x:
  sum+=i
print(x)
print("Sum of random array is ",sum)

[76 16 27 99  4]
Sum of random array is  222


### 2. Write a Python Program to find largest element in an array?


In [3]:
mx=0
for i in x:
  mx=max(mx,i)
print("Maximum element is ",mx)

Maximum element is  99


### 3. Write a Python Program for array rotation?

In [17]:
def rotation(p):
  n=len(p)
  for i in range(0,int(n/2)+1):
    t=p[i]
    p[i]=p[n-i-1]
    p[n-i-1]=t
  return p
a=x.copy()
print(x,": without rotation")
print(rotation(a),": rotation")

[ 4 99 27 16 76] : without rotation
[76 16 27 99  4] : rotation


### 4. Write a Python Program to Split the array and add the first part to the end?

In [28]:
import numpy as np
n=int(len(x)/2)
arr1 = x[n:]
arr2=x[:n]
np.concatenate((arr1,arr2))

array([27, 16, 76,  4, 99])

### 5. Write a Python Program to check if given array is Monotonic?

In [29]:
def isMonotonic(arry):
  flag_inc=True; flag_dec=True
  for i in range(1,len(arry)):
    if arry[i-1]<arry[i]:
      flag_dec=False
    if arry[i-1]>arry[i]:
      flag_inc=False
  return flag_inc or flag_dec

In [30]:
isMonotonic(x)

False